name: 'Redis Deployment'
description: 'Deploy Redis in an EC2 instance'
inputs:
  redis-server:
    description: 'Redis server'
    required: true
  redis-version:
    description: 'Redis version'
    required: true
    default: '6'
  instance-name:
    description: 'Redis instance name'
    required: true
  instance-port:
    description: 'Redis instance port'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ secrets.REDIS_MASTER_SSH_KEY }}" > redis.pem
      shell: bash
    - run: chmod 600 redis-server.pem
      shell: bash
    - run: ansible-playbook ${{ github.action_path }}/deploy-redis.yaml -i ${{ inputs.redis-server }}, --key-file "redis-server.pem" -e "instance_name=${{ inputs.instance-name }}" -e "instance_port=${{ instance-port }}"
      shell: bash
