name: 'Redis Deployment'
description: 'Deploy Redis in an EC2 instance'
inputs:
  redis-server:
    description: 'Redis server'
    required: true
  redis-version:
    description: 'Redis version'
    required: true
    default: '6'
  redis-password:
    description: 'Redis password'
    required: true
  event-number:
    description: 'Pull Request number'
    required: true
  ssh-key:
    description: 'Redis instance ssh key'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.ssh-key }}" > redis-server.pem
      shell: bash
    - run: chmod 600 redis-server.pem
      shell: bash
    - run: pwd 
      shell: bash
    - run: echo "REDIS_PORT=$((30000 + ${{ inputs.event-number }}))" >> "$GITHUB_ENV"
      shell: bash
    - run: ansible-playbook ${{ github.action_path }}/deploy-redis.yaml -i ${{ inputs.redis-server }}, --key-file "redis-server.pem" -e "instance_name=redis-pr-${{ inputs.event-number }}" -e "instance_port=$REDIS_PORT" -e "redis_password=$REDIS_PASSWORD"
      shell: bash
