- hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: create redis instance
    tags:
      - deploy 
    docker_container:
      name: "{{ instance_name }}"
      image: redis:{{ redis_version }}-alpine
      command: redis-server --requirepass {{ redis_password }}
      state: started
      detach: True
      restart_policy: always
      ports:
        - "{{ instance_port }}:6379"
      volumes:
      - /data
  - name: delete redis instance
    tags:
      - destroy
    docker_container:
      name: "{{ instance_name }}"
      state: absent
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
