name: Test

on:
  push

jobs:
  deploy:
    name: Test the Redis Deployment Action
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Redis
        uses: ableco/action-redis-deployment@main
        with:
          redis-version: 6
          redis-server: ${{ secrets.REDIS_MASTER_HOST }}
          redis-password: ${{ secrets.REDIS_MASTER_PASSWORD }}
          event-number: 25
          ssh-key: ${{ secrets.REDIS_SSH_KEY }}
          instance: redis-test
